"""
ASGI config for config project.

It exposes the ASGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/howto/deployment/asgi/
"""

import os

from django.core.asgi import get_asgi_application

# NOTE: this project actually deploys via WSGI/gunicorn (see wsgi.py and the
# Procfile's `web: gunicorn config.wsgi:application`), not ASGI — this file
# is Django's default scaffolding, generated by `startproject` but not
# currently wired into the deployment. It would only start mattering if
# something async-native were added later (e.g. websockets, ASGI-only
# middleware) and the deploy target were switched to an ASGI server
# (uvicorn/daphne) instead of gunicorn.
#
# Also note the default below points at "config.settings" (the settings
# *package*, which only contains base/local/production submodules and no
# settings of its own) rather than "config.settings.local" or
# "config.settings.production" like manage.py/wsgi.py use — since this file
# isn't part of the live request path, that mismatch has no practical effect
# today, but it would need correcting before ASGI were ever actually used.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')

application = get_asgi_application()
