# Generated by Django 6.1 on 2026-08-23 06:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionIssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_stem_snapshot', models.TextField(blank=True)),
                ('question_number_in_quiz', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_type', models.CharField(choices=[('ANSWER_INCORRECT', 'Answer may be incorrect'), ('UNCLEAR', 'Question is unclear'), ('RATIONALE_NEEDS_IMPROVEMENT', 'Rationale needs improvement'), ('CLINICAL_INFO_INCORRECT', 'Clinical information seems incorrect'), ('TYPO_GRAMMAR', 'Typo/grammar'), ('REFERENCE_ISSUE', 'Reference issue'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_reports', to='questions.question')),
                ('quiz_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_reports', to='quizzes.quizsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_issue_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('question_quality_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('difficulty_rating', models.CharField(choices=[('MUCH_TOO_EASY', 'Much too easy'), ('SOMEWHAT_EASY', 'Somewhat easy'), ('JUST_RIGHT', 'Just right'), ('SOMEWHAT_DIFFICULT', 'Somewhat difficult'), ('MUCH_TOO_DIFFICULT', 'Much too difficult')], max_length=20)),
                ('realism_rating', models.CharField(choices=[('NOT_REALISTIC', 'Not realistic'), ('SLIGHTLY_REALISTIC', 'Slightly realistic'), ('MODERATELY_REALISTIC', 'Moderately realistic'), ('VERY_REALISTIC', 'Very realistic'), ('EXTREMELY_REALISTIC', 'Extremely realistic')], max_length=25)),
                ('rationale_helpfulness_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('had_question_issue', models.BooleanField(default=False)),
                ('issue_question_number', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_description', models.TextField(blank=True)),
                ('liked_most', models.TextField(blank=True)),
                ('improvement_suggestion', models.TextField(blank=True)),
                ('recommend_likelihood', models.CharField(choices=[('DEFINITELY_NOT', 'Definitely not'), ('PROBABLY_NOT', 'Probably not'), ('MAYBE', 'Maybe'), ('PROBABLY_YES', 'Probably yes'), ('DEFINITELY_YES', 'Definitely yes')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='quizzes.quizsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quiz feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
