# Generated by Django 6.1 on 2026-09-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfeedback',
            name='status',
            field=models.CharField(choices=[('IN_CONSIDERATION', 'In consideration'), ('IMPLEMENTED', 'Implemented'), ('REJECTED', 'Rejected')], default='IN_CONSIDERATION', max_length=20),
        ),
        migrations.AddField(
            model_name='quizfeedback',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
