from django.conf import settings
# Django's built-in mail-sending function — which backend actually delivers
# the message (console print in dev, SendGrid via Anymail in production) is
# decided entirely by EMAIL_BACKEND in settings, so this file never needs to
# know or care which environment it's running in.
from django.core.mail import send_mail

from .tokens import make_verification_token


def send_verification_email(user):
    # Generates a signed, self-verifying token for this specific user (see
    # tokens.py) — no separate "PendingVerification" DB row needed.
    token = make_verification_token(user.pk)
    # Points at the React frontend's /verify-email route (not an API URL) —
    # the user clicks this link in their inbox, the frontend page then calls
    # GET /api/auth/verify-email/<token>/ itself. FRONTEND_URL is
    # environment-specific (localhost:5173 in dev, the real domain in prod).
    verify_url = f"{settings.FRONTEND_URL}/verify-email?token={token}"
    send_mail(
        subject="Verify your NextWise Education account",
        message=f"Welcome to NextWise Education. Verify your email to activate your account:\n\n{verify_url}",
        from_email=settings.DEFAULT_FROM_EMAIL,
        recipient_list=[user.email],
    )


def send_password_reset_email(user, uid, token):
    # uid/token are generated by the caller (PasswordResetRequestView, using
    # Django's own default_token_generator + base64-encoded pk) rather than
    # by this module — kept as plain parameters here so this function stays
    # a pure "format and send" step with no knowledge of how the token was
    # produced.
    reset_url = f"{settings.FRONTEND_URL}/reset-password?uid={uid}&token={token}"
    send_mail(
        subject="Reset your NextWise Education password",
        message=f"Reset your password using the link below:\n\n{reset_url}",
        from_email=settings.DEFAULT_FROM_EMAIL,
        recipient_list=[user.email],
    )
