import logging

from django.conf import settings

# Django's built-in mail-sending function — which backend actually delivers
# the message (console print in dev, Resend via Anymail in production) is
# decided entirely by EMAIL_BACKEND in settings, so this file never needs to
# know or care which environment it's running in.
from django.core.mail import send_mail

from .tokens import make_verification_token

logger = logging.getLogger(__name__)


def send_verification_email(user):
    # Generates a signed, self-verifying token for this specific user (see
    # tokens.py) — no separate "PendingVerification" DB row needed.
    token = make_verification_token(user.pk)
    # Points at the React frontend's /verify-email route (not an API URL) —
    # the user clicks this link in their inbox, the frontend page then calls
    # GET /api/auth/verify-email/<token>/ itself. FRONTEND_URL is
    # environment-specific (localhost:5173 in dev, the real domain in prod).
    verify_url = f"{settings.FRONTEND_URL}/verify-email?token={token}"
    # Caller (RegisterView) must still return 201 even if the send itself
    # fails (e.g. Resend misconfigured/down) — the account already exists
    # at this point, and surfacing a 500 here would strand it: the student
    # can't register again (email taken) and got no usable error to act on.
    # Swallow-and-log means the failure shows up in logs/monitoring instead
    # of as a broken signup for the student.
    try:
        send_mail(
            subject="Verify your NextWise Education account",
            message=f"Welcome to NextWise Education. Verify your email to activate your account:\n\n{verify_url}",
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
        )
    except Exception:
        logger.exception("Failed to send verification email to %s", user.email)


def send_password_reset_email(user, uid, token):
    # uid/token are generated by the caller (PasswordResetRequestView, using
    # Django's own default_token_generator + base64-encoded pk) rather than
    # by this module — kept as plain parameters here so this function stays
    # a pure "format and send" step with no knowledge of how the token was
    # produced.
    reset_url = f"{settings.FRONTEND_URL}/reset-password?uid={uid}&token={token}"
    # Same reasoning as send_verification_email above: the caller always
    # responds with the same generic "if that email is registered..." 200
    # regardless of what happens here, so a raised exception would turn into
    # an unhandled 500 instead of that intended generic response.
    try:
        send_mail(
            subject="Reset your NextWise Education password",
            message=f"Reset your password using the link below:\n\n{reset_url}",
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
        )
    except Exception:
        logger.exception("Failed to send password reset email to %s", user.email)


def send_duplicate_registration_email(user):
    """
    Sent when someone submits the registration form with an email address
    that already has an account.

    The register endpoint deliberately responds with the same generic 201 in
    that case as it does for a brand-new account, so it can't be used to
    enumerate which addresses are registered here. That silence has to go
    somewhere useful though: this email is the "somewhere". The real owner
    of the address finds out an attempt was made and is told what to do
    (log in, or reset the password), while whoever submitted the form
    learns nothing at all — they get the same response either way and this
    message goes to the account holder's inbox, not theirs.

    Deliberately says nothing about the submitted password or full name,
    and creates nothing: it is purely a notification about an attempt.
    """
    login_url = f"{settings.FRONTEND_URL}/login"
    reset_url = f"{settings.FRONTEND_URL}/forgot-password"
    # Same swallow-and-log reasoning as the two senders above: RegisterView
    # must return its generic 201 whatever happens here, or the difference
    # between "email sent fine" and "email provider hiccuped" would itself
    # become the enumeration signal this whole design exists to remove.
    try:
        send_mail(
            subject="Someone tried to register with your NextWise Education email",
            message=(
                "Someone just tried to create a NextWise Education account using this email address, "
                "which already has an account.\n\n"
                "If that was you, you already have an account — sign in here:\n"
                f"{login_url}\n\n"
                "If you have forgotten your password, you can reset it here:\n"
                f"{reset_url}\n\n"
                "If it wasn't you, you can safely ignore this email. No new account was created and "
                "nothing about your existing account has changed."
            ),
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
        )
    except Exception:
        logger.exception("Failed to send duplicate-registration notice to %s", user.email)
