# Django's signing utilities — used here to build a self-contained,
# tamper-proof "email verification token" without needing a database table
# to track pending verifications. BadSignature is raised for a
# forged/corrupted token; SignatureExpired for one that's simply too old.
from django.core.signing import BadSignature, SignatureExpired, TimestampSigner

# TimestampSigner signs a value with the SECRET_KEY and embeds a timestamp,
# so later we can both verify the value wasn't tampered with AND check how
# old it is. `salt` namespaces this signer so a token generated here can't
# be replayed against some other part of the app that also uses
# TimestampSigner with a different salt (e.g. password reset uses Django's
# own separately-salted default_token_generator instead, see views.py).
_signer = TimestampSigner(salt="email-verification")

# 3 days — how long a "verify your email" link stays clickable after
# registration before the user would need to re-register (there's currently
# no separate "resend verification" endpoint).
VERIFICATION_TOKEN_MAX_AGE_SECONDS = 60 * 60 * 24 * 3  # 3 days


def make_verification_token(user_id) -> str:
    # Signs the user's UUID (as a string) into an opaque token like
    # "<uuid>:<timestamp>:<signature>" — this token IS the payload, so
    # nothing needs to be stored server-side to later validate it; the
    # signature alone proves it was generated by this server and hasn't
    # been altered.
    return _signer.sign(str(user_id))


def read_verification_token(token: str) -> str | None:
    """Returns the user id encoded in the token, or None if invalid/expired."""
    try:
        # unsign() re-verifies the signature against SECRET_KEY and checks
        # the embedded timestamp against max_age — raises if either check
        # fails, rather than returning a falsy value, hence the try/except.
        return _signer.unsign(token, max_age=VERIFICATION_TOKEN_MAX_AGE_SECONDS)
    except (BadSignature, SignatureExpired):
        # Both a forged/corrupted token (BadSignature) and a legitimately
        # expired one (SignatureExpired) are treated identically by the
        # caller (VerifyEmailView) — the user just sees "invalid or expired
        # link" either way, since there's no useful different action to take.
        return None
