# Generated by Django 6.1 on 2026-08-20 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClozeBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_key', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='DragDropCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ClozeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.clozeblank')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice (single answer)'), ('SATA', 'Select All That Apply'), ('MATRIX', 'Matrix/Grid'), ('BOWTIE', 'Bow-Tie'), ('EMR', 'Extended Multiple Response'), ('DRAG_DROP', 'Drag and Drop'), ('CLOZE', 'Drop-down Cloze'), ('HOTSPOT', 'Enhanced Hot Spot'), ('NGN_CASE', 'NGN Case Study')], max_length=20)),
                ('ngn_type', models.CharField(blank=True, choices=[('MCQ', 'Multiple Choice (single answer)'), ('SATA', 'Select All That Apply'), ('MATRIX', 'Matrix/Grid'), ('BOWTIE', 'Bow-Tie'), ('EMR', 'Extended Multiple Response'), ('DRAG_DROP', 'Drag and Drop'), ('CLOZE', 'Drop-down Cloze'), ('HOTSPOT', 'Enhanced Hot Spot'), ('NGN_CASE', 'NGN Case Study')], max_length=20, null=True)),
                ('stem', models.TextField()),
                ('clinical_scenario', models.TextField(blank=True, null=True)),
                ('case_study_sequence', models.IntegerField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='question_images/')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('clinical_judgment_skill', models.CharField(choices=[('RECOGNIZE_CUES', 'Recognize Cues'), ('ANALYZE_CUES', 'Analyze Cues'), ('PRIORITIZE_HYPOTHESES', 'Prioritize Hypotheses'), ('GENERATE_SOLUTIONS', 'Generate Solutions'), ('TAKE_ACTION', 'Take Action'), ('EVALUATE_OUTCOMES', 'Evaluate Outcomes')], max_length=25)),
                ('cognitive_level', models.CharField(choices=[('REMEMBER', 'Remember'), ('UNDERSTAND', 'Understand'), ('APPLY', 'Apply'), ('ANALYZE', 'Analyze'), ('EVALUATE', 'Evaluate'), ('CREATE', 'Create')], max_length=15)),
                ('rationale_correct', models.TextField()),
                ('rationale_incorrect', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('case_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='taxonomy.casestudy')),
                ('nclex_client_needs_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='taxonomy.clientneedscategory')),
                ('nclex_client_needs_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='taxonomy.clientneedssubcategory')),
                ('nursing_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='taxonomy.nursingsystem')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='taxonomy.subtopic')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='taxonomy.tag')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='taxonomy.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatrixRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_rows', to='questions.question')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MatrixColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_columns', to='questions.question')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HotSpotTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_targets', to='questions.question')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='DragDropItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('correct_order', models.IntegerField(blank=True, null=True)),
                ('correct_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='questions.dragdropcategory')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragdrop_items', to='questions.question')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='dragdropcategory',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragdrop_categories', to='questions.question'),
        ),
        migrations.AddField(
            model_name='clozeblank',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloze_blanks', to='questions.question'),
        ),
        migrations.CreateModel(
            name='BowTieOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('ASSESSMENT', 'Assessment'), ('CONDITION', 'Condition'), ('ACTION', 'Action')], max_length=15)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowtie_options', to='questions.question')),
            ],
            options={
                'ordering': ['section', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choices', to='questions.question')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MatrixCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='questions.matrixcolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='questions.matrixrow')),
            ],
            options={
                'unique_together': {('row', 'column')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='clozeblank',
            unique_together={('question', 'blank_key')},
        ),
    ]
