# Generated by Django 6.1 on 2026-08-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='rationale_correct',
            field=models.TextField(blank=True, null=True),
        ),
    ]
