# Generated by Django 6.1 on 2026-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answerchoice_rationale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='key_takeaway',
            field=models.TextField(blank=True, null=True),
        ),
    ]
