# Generated by Django 6.1 on 2026-08-31 07:17

import apps.questions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_key_takeaway'),
        ('taxonomy', '0002_alter_clientneedscategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clozeblank',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='matrixcell',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='external_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='question_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp']), apps.questions.models.validate_question_image_size]),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', 'question_type', 'difficulty', '-created_at'], name='question_active_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['nursing_system', 'topic'], name='question_taxonomy_idx'),
        ),
        migrations.AddConstraint(
            model_name='clozeblank',
            constraint=models.UniqueConstraint(fields=('question', 'blank_key'), name='unique_cloze_blank_key_per_question'),
        ),
        migrations.AddConstraint(
            model_name='matrixcell',
            constraint=models.UniqueConstraint(fields=('row', 'column'), name='unique_matrix_cell_per_row_column'),
        ),
    ]
