# Generated by Django 6.1 on 2026-08-31 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_clozeblank_unique_together_and_more'),
        ('taxonomy', '0003_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='taxonomy.domain'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', 'domain'], name='question_domain_idx'),
        ),
    ]
