# Generated by Django 6.1 on 2026-08-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_domain_question_question_domain_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='clinical_judgment_skill_secondary',
            field=models.CharField(blank=True, choices=[('RECOGNIZE_CUES', 'Recognize Cues'), ('ANALYZE_CUES', 'Analyze Cues'), ('PRIORITIZE_HYPOTHESES', 'Prioritize Hypotheses'), ('GENERATE_SOLUTIONS', 'Generate Solutions'), ('TAKE_ACTION', 'Take Action'), ('EVALUATE_OUTCOMES', 'Evaluate Outcomes')], max_length=25, null=True),
        ),
    ]
