# Generated by Django 6.1 on 2026-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_clinical_judgment_skill_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowtieoption',
            name='rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clozeoption',
            name='rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dragdropitem',
            name='rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotspottarget',
            name='rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matrixcell',
            name='rationale',
            field=models.TextField(blank=True),
        ),
    ]
