# Generated by Django 6.1 on 2026-09-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_importlog'),
        ('taxonomy', '0004_casestudy_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragdropitem',
            name='correct_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='questions.dragdropcategory'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('case_study__isnull', False)), fields=('case_study', 'case_study_sequence'), name='unique_case_study_sequence'),
        ),
    ]
