# Generated by Django 6.1 on 2026-08-31 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_domain_question_question_domain_idx'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='questions.question')),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='quizzes.quizsession')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        # Django can't ALTER a bare M2M into a through= M2M in place ("you
        # cannot alter to or from M2M fields, or add or remove through= on
        # M2M fields") — remove + re-add instead. Safe as a schema-only
        # change: QuizSession has never had a view that creates one, so this
        # table is empty in every environment this migration will ever run
        # against (confirmed before writing this migration, not assumed).
        migrations.RemoveField(
            model_name='quizsession',
            name='questions',
        ),
        migrations.AddField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(related_name='quiz_sessions', through='quizzes.QuizSessionQuestion', to='questions.question'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='questions.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'question'), name='unique_bookmark_per_student_question')],
            },
        ),
        migrations.AddConstraint(
            model_name='quizsessionquestion',
            constraint=models.UniqueConstraint(fields=('quiz_session', 'position'), name='unique_position_per_session'),
        ),
        migrations.AddConstraint(
            model_name='quizsessionquestion',
            constraint=models.UniqueConstraint(fields=('quiz_session', 'question'), name='unique_question_per_session'),
        ),
    ]
