# Generated by Django 6.1 on 2026-08-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizsessionquestion_alter_quizsession_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponselog',
            name='selected_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
