# Generated by Django 6.1 on 2026-09-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_studentresponselog_selected_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='is_abandoned',
            field=models.BooleanField(default=False),
        ),
    ]
