# Generated by Django 6.1 on 2026-09-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizsession_is_abandoned'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsessionquestion',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
