# Generated by Django 6.1 on 2026-09-08 07:38

from django.db import migrations, models
from django.db.models import Count


def backfill_total_questions(apps, schema_editor):
    """
    Existing rows would otherwise sit at the field's default (0), which
    QuizAnswerSubmitView's auto-complete check reads as "every question
    answered" on the very next submission for any of them — silently
    completing whatever quiz sessions were already in progress when this
    migration runs.
    """
    QuizSession = apps.get_model("quizzes", "QuizSession")
    for session in QuizSession.objects.annotate(actual_total=Count("session_questions")):
        session.total_questions = session.actual_total
        session.save(update_fields=["total_questions"])


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quizsessionquestion_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_total_questions, migrations.RunPython.noop),
    ]
