# Generated by Django 6.1 on 2026-08-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disclaimer_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='disclaimer_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
