# Generated by Django 6.1 on 2026-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_terms_accepted_at_user_terms_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('CONTENT_ADMIN', 'Content admin'), ('SUPERUSER', 'Superuser')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
