# Generated by Django 6.1 on 2026-08-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_question_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
