# Generated by Django 6.1 on 2026-08-20 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('shared_scenario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NursingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientNeedsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('RN', 'NCLEX-RN'), ('PN', 'NCLEX-PN')], default='RN', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Client Needs categories',
                'ordering': ['exam_type', 'name'],
                'unique_together': {('name', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nursing_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='taxonomy.nursingsystem')),
            ],
            options={
                'ordering': ['nursing_system__name', 'name'],
                'unique_together': {('nursing_system', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClientNeedsSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='taxonomy.clientneedscategory')),
            ],
            options={
                'verbose_name_plural': 'Client Needs subcategories',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='taxonomy.topic')),
            ],
            options={
                'ordering': ['topic__name', 'name'],
                'unique_together': {('topic', 'name')},
            },
        ),
    ]
