# Generated by Django 6.1 on 2026-08-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientneedscategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='clientneedssubcategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='clientneedscategory',
            constraint=models.UniqueConstraint(fields=('name', 'exam_type'), name='unique_client_needs_category_per_exam_type'),
        ),
        migrations.AddConstraint(
            model_name='clientneedssubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_client_needs_subcategory_per_category'),
        ),
        migrations.AddConstraint(
            model_name='subtopic',
            constraint=models.UniqueConstraint(fields=('topic', 'name'), name='unique_subtopic_name_per_topic'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('nursing_system', 'name'), name='unique_topic_name_per_nursing_system'),
        ),
    ]
