# Generated by Django 6.1 on 2026-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='external_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
