export const ROUTES = {
  home: "/",
  register: "/register",
  login: "/login",
  verifyEmail: "/verify-email",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  quizSetup: "/quiz",
  quizSession: "/quiz/session",
  quizResults: "/quiz/results",
  privacyPolicy: "/privacy-policy",
  termsAndConditions: "/terms-and-conditions",
  accessibility: "/accessibility",
  faq: "/faq",
} as const;
